repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        additional_dependencies: []

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        additional_dependencies: []

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        args: ["--fix"]
        additional_dependencies: []
