runtime: python310
instance_class: F2
env: standard
entrypoint: gunicorn -w 4 -b :$PORT dashapp.main:server
automatic_scaling:
  min_instances: 0
  max_instances: 5

env_variables:
  USER_AGENT: "A chess.com analysis by DataWizards"
  PORT: "8080"
